get_example_data:
	gdal_translate -srcwin 10000 8000 1000 1000 "/home/hemi/Nextcloud/Shared/2023/2023-03-15 Præcisionsfrøavl - data/Processed/2023-03-17 Alm. rajgræs Cleopatra JSJ 1/orthomosaics/2023-03-17 alm. rajgræs Cleopatra JSJ 1_ORTHO.tif" 2023-03-17_Alm_rajgraes_cleopatra_jsj.tif


get_example_data_2:
	gdal_translate -srcwin 10000 8000 1000 1000 "/home/hemi/Nextcloud/Shared/2023/2023-03-15 Præcisionsfrøavl - data/Processed/2023-04-03 Alm. rajgræs Cleopatra JSJ 2/orthomosaics/2023-04-03 Alm. rajgræs Cleopatra JSJ 2_ORTHO.tif" 2023-04-03_Alm_rajgraes_cleopatra_jsj.tif


get_example_data_3:
	gdal_translate -srcwin 10000 8000 1000 1000 "/home/hemi/Nextcloud/Shared/2023/2023-03-15 Præcisionsfrøavl - data/Processed/2023-04-17 Alm. rajgræs Cleopatra JSJ 3/orthomosaics/2023-04-17 Alm. rajgræs Cleopatra JSJ 3_ORTHO.tif" 2023-04-17_Alm_rajgraes_cleopatra_jsj.tif


get_example_data_4:
	gdal_translate -srcwin 10000 8000 1000 1000 "/home/hemi/Nextcloud/Shared/2023/2023-03-15 Præcisionsfrøavl - data/Processed/2023-05-01 Alm. rajgræs Cleopatra JSJ 4/orthomosaics/2023-05-01 Alm. rajgræs Cleopatra JSJ 4_ORTHO.tif" 2023-05-01_Alm_rajgraes_cleopatra_jsj.tif

