get_example_data:
	gdal_translate -srcwin 10000 8000 1000 1000 "/home/hemi/Nextcloud/Shared/2023/2023-03-15 Præcisionsfrøavl - data/Processed/2023-03-17 Alm. rajgræs Cleopatra JSJ 1/orthomosaics/2023-03-17 alm. rajgræs Cleopatra JSJ 1_ORTHO.tif" 2023-03-17_Alm_rajgraes_cleopatra_jsj.tif
